# Generated by Django 4.2.4 on 2023-08-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_empid_alter_student_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
